#!/system/xbin/bash
#RPKG 1.0

#PRE: Check if we have root access
if [ "$(id -u)" != "0" ]; then
    echo "$0 must be run by root to work properly!";
    exit 1;
fi;
#Remount /system rw
mount -o remount,rw /system;
#Make Temporary Directory
if [ ! -e /etc/rptemp ]; then
	mkdir /etc/rptemp;
fi;
mount -t tmpfs tmpfs /etc/rptemp;

#PRE: Check if all prerequisites are met
echo "($(date)) ======[Prerequisites check]======" >> /etc/rpkg.log
[ ! -e /etc/rpkg ] && echo RPKG is not properly installed! && echo "($(date)) RPKG not installed, exit 1ing..." >> /etc/rpkg.log && exit 1
[ ! -f /etc/rpkg/sources ] && echo No sources have been added! Please add some before installing anything! && echo "($(date)) RPKG cannot find /etc/rpkg/sources, exiting..." >> /etc/rpkg.log && exit 1
[ ! -e /etc/rpkg/packages ] && mkdir /etc/rpkg/packages

#PH1: Iterate through all sources and download all package files
while read srcline; do
	wget $srcline/pkinfo -O /etc/rptemp/packages -o /etc/rptemp/pkgtrans.bak
	cd /etc/rpkg/packages
	while read packageline; do
		wget $packageline -o /etc/rptemp/pkgtrans00.bak
	done <"/etc/rptemp/packages";
done <"/etc/rpkg/sources";
